rvm:
  - 2.2.10
  - 2.5.3

gemfile:
  - Gemfile.cucumber-1.3
  - Gemfile.cucumber-2.4
  - Gemfile.cucumber-3.0
  - Gemfile.cucumber-3.1

dist: trusty

matrix:
  exclude:
    - gemfile: Gemfile.cucumber-3.1
      rvm: 2.2.10 # cucumber 3 wants ruby >= 2.2
    - gemfile: Gemfile.cucumber-3.0
      rvm: 2.2.10 # cucumber 3 wants ruby >= 2.2
    - gemfile: Gemfile.cucumber-1.3
      rvm: 2.5.3 # doesn't work with old RSpec

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec

sudo: false

cache: bundler
