rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9

gemfile:
  - gemfiles/Gemfile.cucumber-3.1
  - gemfiles/Gemfile.cucumber-3.0

matrix:
  exclude:

before_install:
  # Work around travis issue https://github.com/travis-ci/travis-ci/issues/8969
  - gem update --system

install:
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec

sudo: false

cache: bundler

notifications:
  email:
    - fail@makandra.de
